# Generated by Django 3.2.16 on 2022-11-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='clothing',
            field=models.CharField(choices=[
                ('warm', 'Warm'),
                ('comfy ', 'Comfy'),
                ('swimming', 'Swimming'),
                ('fancy', 'Fancy')],
                default='comfy',
                max_length=32
            ),
        ),
    ]
